// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFjsRMh3dVEphpEiE9hOSEdNkch2ouuow',
    appId: '1:988630261528:web:20a8a6b6437b490758c86d',
    messagingSenderId: '988630261528',
    projectId: 'brikool-dev',
    authDomain: 'brikool-dev.firebaseapp.com',
    databaseURL: 'https://brikool-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'brikool-dev.firebasestorage.app',
    measurementId: 'G-CHY37NE73B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-CUA9C9M2SbKoWvuEun2NF5ELD2bs6Hc',
    appId: '1:988630261528:android:dd79eb377398610458c86d',
    messagingSenderId: '988630261528',
    projectId: 'brikool-dev',
    databaseURL: 'https://brikool-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'brikool-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcda3fvAqlRGbt-gEsVlOihjpZCILhkB0',
    appId: '1:988630261528:ios:b7606a3c1d6eaf4658c86d',
    messagingSenderId: '988630261528',
    projectId: 'brikool-dev',
    databaseURL: 'https://brikool-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'brikool-dev.firebasestorage.app',
    iosBundleId: 'com.example.brikoolMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcda3fvAqlRGbt-gEsVlOihjpZCILhkB0',
    appId: '1:988630261528:ios:b7606a3c1d6eaf4658c86d',
    messagingSenderId: '988630261528',
    projectId: 'brikool-dev',
    databaseURL: 'https://brikool-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'brikool-dev.firebasestorage.app',
    iosBundleId: 'com.example.brikoolMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFjsRMh3dVEphpEiE9hOSEdNkch2ouuow',
    appId: '1:988630261528:web:161c3fefe71f425b58c86d',
    messagingSenderId: '988630261528',
    projectId: 'brikool-dev',
    authDomain: 'brikool-dev.firebaseapp.com',
    databaseURL: 'https://brikool-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'brikool-dev.firebasestorage.app',
    measurementId: 'G-Z90C9VR8KN',
  );
}
